CREATE OR REPLACE PACKAGE PACK_EQUIPAMENTO AS
    FUNCTION FUNC_PROXIMO RETURN NUMBER;
    FUNCTION FUNC_EXISTE_UID(P_INTERNAL_UID IN VARCHAR2) RETURN NUMBER;
    FUNCTION FUNC_STATUS_DESCRICAO(P_STATUS IN VARCHAR2) RETURN VARCHAR2;

    PROCEDURE PROC_INSERT(
        P_INTERNAL_UID IN VARCHAR2,
        P_SERIAL_NUMBER IN VARCHAR2,
        P_MODELO IN VARCHAR2,
        P_MARCA IN VARCHAR2,
        P_PROCESSADOR IN VARCHAR2,
        P_RAM_GB IN NUMBER,
        P_STORAGE_GB IN NUMBER,
        P_CONDITION_STATUS IN VARCHAR2,
        P_STATUS_EQUIPAMENTO IN VARCHAR2,
        P_OBSERVACAO IN VARCHAR2
    );

    PROCEDURE PROC_UPDATE_STATUS(
        P_INTERNAL_UID IN VARCHAR2,
        P_STATUS IN VARCHAR2
    );

    PROCEDURE PROC_UPSERT_EQUIPAMENTO(
        P_INTERNAL_UID IN VARCHAR2,
        P_SERIAL_NUMBER IN VARCHAR2,
        P_MODEL IN VARCHAR2,
        P_MARCA IN VARCHAR2,
        P_PROCESSADOR IN VARCHAR2,
        P_RAM_GB IN NUMBER,
        P_STORAGE_GB IN NUMBER,
        P_CONDITION_STATUS IN VARCHAR2,
        P_STATUS IN VARCHAR2,
        P_OBSERVACAO IN VARCHAR2
    );

    PROCEDURE PROC_SELECT_UID(
        P_INTERNAL_UID IN VARCHAR2,
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_FILTRO(
        P_FILTRO IN VARCHAR2,
        P_STATUS_EQUIPAMENTO IN VARCHAR2,
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_DASHBOARD(
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_ID(
        P_ID IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_SERIAL(
        P_SERIAL IN VARCHAR2,
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_RESUMO_WHATSAPP(
        P_CURSOR OUT SYS_REFCURSOR
    );
END PACK_EQUIPAMENTO;
/
