CREATE OR REPLACE PACKAGE PACK_UPGRADE AS
    PROCEDURE PROC_INSERT_UPGRADE(
        P_ID_EQUIPAMENTO IN NUMBER,
        P_TIPO_UPGRADE IN VARCHAR2,
        P_RAM_ANTERIOR_GB IN NUMBER,
        P_RAM_NOVA_GB IN NUMBER,
        P_STORAGE_ANTERIOR_GB IN NUMBER,
        P_STORAGE_NOVO_GB IN NUMBER,
        P_TECNICO IN VARCHAR2,
        P_OBSERVACAO IN VARCHAR2
    );

    PROCEDURE PROC_SELECT_EQUIPAMENTO(
        P_ID_EQUIPAMENTO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );
END PACK_UPGRADE;
/

CREATE OR REPLACE PACKAGE BODY PACK_UPGRADE AS

    PROCEDURE PROC_INSERT_UPGRADE(
        P_ID_EQUIPAMENTO      IN NUMBER,
        P_TIPO_UPGRADE        IN VARCHAR2,
        P_RAM_ANTERIOR_GB     IN NUMBER,
        P_RAM_NOVA_GB         IN NUMBER,
        P_STORAGE_ANTERIOR_GB IN NUMBER,
        P_STORAGE_NOVO_GB     IN NUMBER,
        P_TECNICO             IN VARCHAR2,
        P_OBSERVACAO          IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO TBL_EQUIPAMENTO_UPGRADE (
            ID_UPGRADE, ID_EQUIPAMENTO, TIPO_UPGRADE,
            RAM_ANTERIOR_GB, RAM_NOVA_GB,
            STORAGE_ANTERIOR_GB, STORAGE_NOVO_GB,
            TECNICO, OBSERVACAO, DATA_UPGRADE
        ) VALUES (
            SEQ_EQUIPAMENTO_UPGRADE.NEXTVAL, P_ID_EQUIPAMENTO, P_TIPO_UPGRADE,
            P_RAM_ANTERIOR_GB, P_RAM_NOVA_GB,
            P_STORAGE_ANTERIOR_GB, P_STORAGE_NOVO_GB,
            P_TECNICO, P_OBSERVACAO, SYSDATE
        );

        UPDATE TBL_EQUIPAMENTO
           SET RAM_GB     = CASE WHEN P_RAM_NOVA_GB     > 0 THEN P_RAM_NOVA_GB     ELSE RAM_GB     END,
               STORAGE_GB = CASE WHEN P_STORAGE_NOVO_GB > 0 THEN P_STORAGE_NOVO_GB ELSE STORAGE_GB END,
               STATUS           = 'IN_REPAIR',
               DATA_ATUALIZACAO = SYSDATE
         WHERE ID_EQUIPAMENTO = P_ID_EQUIPAMENTO;
    END;

    PROCEDURE PROC_SELECT_EQUIPAMENTO(
        P_ID_EQUIPAMENTO IN  NUMBER,
        P_CURSOR         OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM TBL_EQUIPAMENTO_UPGRADE
             WHERE ID_EQUIPAMENTO = P_ID_EQUIPAMENTO
             ORDER BY DATA_UPGRADE DESC;
    END;

END PACK_UPGRADE;