CREATE OR REPLACE PACKAGE PACK_REMESSA IS

    PROCEDURE PROC_INSERT_REMESSA(
        P_CODIGO_REMESSA IN VARCHAR2,
        P_DESTINATARIO IN VARCHAR2,
        P_CARRIER IN VARCHAR2,
        P_TRACKING IN VARCHAR2,
        P_OBSERVACAO IN VARCHAR2
    );

    PROCEDURE PROC_ADD_ITEM(
        P_CODIGO_REMESSA IN VARCHAR2,
        P_INTERNAL_UID IN VARCHAR2
    );

    PROCEDURE PROC_UPDATE_STATUS(
        P_CODIGO_REMESSA IN VARCHAR2,
        P_STATUS_REMESSA IN VARCHAR2
    );

    PROCEDURE PROC_SELECT_REMESSAS(
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_ITENS(
        P_CODIGO_REMESSA IN VARCHAR2,
        P_CURSOR OUT SYS_REFCURSOR
    );

END PACK_REMESSA;
/

CREATE OR REPLACE PACKAGE BODY PACK_REMESSA AS

PROCEDURE PROC_INSERT_REMESSA(
    P_CODIGO_REMESSA IN VARCHAR2,
    P_DESTINATARIO IN VARCHAR2,
    P_CARRIER IN VARCHAR2,
    P_TRACKING IN VARCHAR2,
    P_OBSERVACAO IN VARCHAR2
) IS
BEGIN
    INSERT INTO TBL_REMESSA
               (ID_REMESSA, CODIGO_REMESSA, DESTINATARIO, CARRIER,
                TRACKING_NUMBER, STATUS_REMESSA, OBSERVACAO, DATA_CADASTRO)
        VALUES (SEQ_REMESSA.NEXTVAL, P_CODIGO_REMESSA, P_DESTINATARIO,
                P_CARRIER, P_TRACKING, 'LABEL_CREATED', P_OBSERVACAO, SYSDATE);
END;

PROCEDURE PROC_ADD_ITEM(
    P_CODIGO_REMESSA IN VARCHAR2,
    P_INTERNAL_UID IN VARCHAR2
) IS
    V_ID_REMESSA NUMBER;
    V_ID_EQUIP NUMBER;
BEGIN
    SELECT ID_REMESSA INTO V_ID_REMESSA
      FROM TBL_REMESSA WHERE CODIGO_REMESSA = P_CODIGO_REMESSA AND ROWNUM = 1;

    SELECT ID_EQUIPAMENTO INTO V_ID_EQUIP
      FROM TBL_EQUIPAMENTO WHERE INTERNAL_UID = P_INTERNAL_UID AND ROWNUM = 1;

    INSERT INTO TBL_REMESSA_ITEM
               (ID_REMESSA_ITEM, ID_REMESSA, ID_EQUIPAMENTO, STATUS_ITEM, DATA_CADASTRO)
        VALUES (SEQ_REMESSA_ITEM.NEXTVAL, V_ID_REMESSA, V_ID_EQUIP, 'PENDING', SYSDATE);

    UPDATE TBL_EQUIPAMENTO
       SET STATUS = 'SHIPPED', DATA_ATUALIZACAO = SYSDATE
     WHERE ID_EQUIPAMENTO = V_ID_EQUIP;
END;

PROCEDURE PROC_UPDATE_STATUS(
    P_CODIGO_REMESSA IN VARCHAR2,
    P_STATUS_REMESSA IN VARCHAR2
) IS
    V_ID_REMESSA NUMBER;
BEGIN
    SELECT ID_REMESSA INTO V_ID_REMESSA
      FROM TBL_REMESSA WHERE CODIGO_REMESSA = P_CODIGO_REMESSA AND ROWNUM = 1;

    UPDATE TBL_REMESSA
       SET STATUS_REMESSA = UPPER(P_STATUS_REMESSA)
     WHERE ID_REMESSA = V_ID_REMESSA;

    IF UPPER(P_STATUS_REMESSA) = 'DELIVERED' THEN
        UPDATE TBL_REMESSA_ITEM
           SET STATUS_ITEM = 'DELIVERED'
         WHERE ID_REMESSA = V_ID_REMESSA;

        UPDATE TBL_EQUIPAMENTO
           SET STATUS = 'SOLD', DATA_ATUALIZACAO = SYSDATE
         WHERE ID_EQUIPAMENTO IN (
               SELECT ID_EQUIPAMENTO FROM TBL_REMESSA_ITEM WHERE ID_REMESSA = V_ID_REMESSA);
    END IF;
END;

PROCEDURE PROC_SELECT_REMESSAS(
    P_CURSOR OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_CURSOR FOR
         SELECT R.ID_REMESSA,
                R.CODIGO_REMESSA AS REMESSA_REF,
                R.CARRIER,
                R.TRACKING_NUMBER,
                R.DESTINATARIO,
                R.STATUS_REMESSA,
                R.DATA_ENVIO,
                R.DATA_ENTREGA,
                R.OBSERVACAO,
                R.DATA_CADASTRO,
                (SELECT COUNT(*) FROM TBL_REMESSA_ITEM
                  WHERE ID_REMESSA = R.ID_REMESSA) AS TOTAL_ITENS
           FROM TBL_REMESSA R
          ORDER BY R.DATA_CADASTRO DESC;
END;

PROCEDURE PROC_SELECT_ITENS(
    P_CODIGO_REMESSA IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_CURSOR FOR
         SELECT RI.ID_REMESSA_ITEM, RI.STATUS_ITEM, RI.DATA_CADASTRO,
                RI.SALE_PRICE_USD, RI.NOTES,
                E.INTERNAL_UID, E.MARCA, E.MODEL, E.PROCESSADOR,
                E.RAM_GB, E.STORAGE_GB
           FROM TBL_REMESSA_ITEM RI
           JOIN TBL_REMESSA R ON R.ID_REMESSA = RI.ID_REMESSA
           JOIN TBL_EQUIPAMENTO E ON E.ID_EQUIPAMENTO = RI.ID_EQUIPAMENTO
          WHERE R.CODIGO_REMESSA = P_CODIGO_REMESSA
          ORDER BY E.INTERNAL_UID;
END;

END PACK_REMESSA;
/
