CREATE OR REPLACE PACKAGE PACK_CLIENTE IS

    FUNCTION FUNC_PROXIMO_CLIENTE
        RETURN NUMBER;

    PROCEDURE PROC_INSERT_CLIENTE (
        V_NOME_RAZAO     VARCHAR2,
        V_NOME_FANTASIA  VARCHAR2,
        V_DOCUMENTO      VARCHAR2,
        V_EMAIL          VARCHAR2,
        V_TELEFONE       VARCHAR2,
        V_ENDERECO1      VARCHAR2,
        V_ENDERECO2      VARCHAR2,
        V_CIDADE         VARCHAR2,
        V_ESTADO         VARCHAR2,
        V_ZIP_CODE       VARCHAR2,
        V_PAIS           VARCHAR2,
        V_ATIVO          CHAR,
        V_OBSERVACOES    VARCHAR2,
        V_ID             OUT NUMBER);

    PROCEDURE PROC_UPDATE_CLIENTE (
        V_ID             NUMBER,
        V_NOME_RAZAO     VARCHAR2,
        V_NOME_FANTASIA  VARCHAR2,
        V_DOCUMENTO      VARCHAR2,
        V_EMAIL          VARCHAR2,
        V_TELEFONE       VARCHAR2,
        V_ENDERECO1      VARCHAR2,
        V_ENDERECO2      VARCHAR2,
        V_CIDADE         VARCHAR2,
        V_ESTADO         VARCHAR2,
        V_ZIP_CODE       VARCHAR2,
        V_PAIS           VARCHAR2,
        V_ATIVO          CHAR,
        V_OBSERVACOES    VARCHAR2);

    PROCEDURE PROC_DELETE_CLIENTE (V_ID IN NUMBER);

    PROCEDURE PROC_SELECT_CLIENTE (
        V_ID      IN  NUMBER,
        V_CURSOR  OUT SYS_REFCURSOR);

    PROCEDURE PROC_SELECT_CLIENTES (
        V_ATIVO   IN  CHAR,
        V_CURSOR  OUT SYS_REFCURSOR);

    PROCEDURE PROC_SELECT_CLIENTES_FILTRO (
        V_PESQUISA IN  VARCHAR2,
        V_CURSOR   OUT SYS_REFCURSOR);

END PACK_CLIENTE;


CREATE OR REPLACE PACKAGE BODY PACK_CLIENTE IS

FUNCTION FUNC_PROXIMO_CLIENTE
RETURN NUMBER
AS
    V_ID NUMBER;
BEGIN
    SELECT SEQ_CLIENTE.NEXTVAL INTO V_ID FROM DUAL;
    RETURN V_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Erro ao obter proximo ID de cliente: ' || SQLERRM);
END;

PROCEDURE PROC_INSERT_CLIENTE (
    V_NOME_RAZAO     VARCHAR2,
    V_NOME_FANTASIA  VARCHAR2,
    V_DOCUMENTO      VARCHAR2,
    V_EMAIL          VARCHAR2,
    V_TELEFONE       VARCHAR2,
    V_ENDERECO1      VARCHAR2,
    V_ENDERECO2      VARCHAR2,
    V_CIDADE         VARCHAR2,
    V_ESTADO         VARCHAR2,
    V_ZIP_CODE       VARCHAR2,
    V_PAIS           VARCHAR2,
    V_ATIVO          CHAR,
    V_OBSERVACOES    VARCHAR2,
    V_ID             OUT NUMBER)
AS
BEGIN
    V_ID := FUNC_PROXIMO_CLIENTE;

    INSERT INTO TBL_CLIENTE
          (ID_CLIENTE, NOME_RAZAO, NOME_FANTASIA, DOCUMENTO, EMAIL, TELEFONE,
           ENDERECO1, ENDERECO2, CIDADE, ESTADO, ZIP_CODE, PAIS, ATIVO,
           OBSERVACOES, DATA_CADASTRO)
    VALUES
          (V_ID, UPPER(TRIM(V_NOME_RAZAO)), TRIM(V_NOME_FANTASIA), TRIM(V_DOCUMENTO),
           LOWER(TRIM(V_EMAIL)), TRIM(V_TELEFONE), TRIM(V_ENDERECO1), TRIM(V_ENDERECO2),
           TRIM(V_CIDADE), TRIM(V_ESTADO), TRIM(V_ZIP_CODE), NVL(TRIM(V_PAIS),'USA'),
           NVL(UPPER(V_ATIVO),'Y'), V_OBSERVACOES, SYSDATE);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Erro ao incluir cliente: ' || SQLERRM);
END;

PROCEDURE PROC_UPDATE_CLIENTE (
    V_ID             NUMBER,
    V_NOME_RAZAO     VARCHAR2,
    V_NOME_FANTASIA  VARCHAR2,
    V_DOCUMENTO      VARCHAR2,
    V_EMAIL          VARCHAR2,
    V_TELEFONE       VARCHAR2,
    V_ENDERECO1      VARCHAR2,
    V_ENDERECO2      VARCHAR2,
    V_CIDADE         VARCHAR2,
    V_ESTADO         VARCHAR2,
    V_ZIP_CODE       VARCHAR2,
    V_PAIS           VARCHAR2,
    V_ATIVO          CHAR,
    V_OBSERVACOES    VARCHAR2)
AS
BEGIN
    UPDATE TBL_CLIENTE
       SET NOME_RAZAO    = UPPER(TRIM(V_NOME_RAZAO)),
           NOME_FANTASIA = TRIM(V_NOME_FANTASIA),
           DOCUMENTO     = TRIM(V_DOCUMENTO),
           EMAIL         = LOWER(TRIM(V_EMAIL)),
           TELEFONE      = TRIM(V_TELEFONE),
           ENDERECO1     = TRIM(V_ENDERECO1),
           ENDERECO2     = TRIM(V_ENDERECO2),
           CIDADE        = TRIM(V_CIDADE),
           ESTADO        = TRIM(V_ESTADO),
           ZIP_CODE      = TRIM(V_ZIP_CODE),
           PAIS          = NVL(TRIM(V_PAIS), 'USA'),
           ATIVO         = NVL(UPPER(V_ATIVO), 'Y'),
           OBSERVACOES   = V_OBSERVACOES,
           DATA_ALTERACAO = SYSDATE
     WHERE ID_CLIENTE = V_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Cliente nao encontrado para alteracao: ID=' || V_ID);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

-- CORRECAO [BAIXO]: Verificacao de existencia do ID antes de agir.
PROCEDURE PROC_DELETE_CLIENTE (V_ID IN NUMBER)
AS
    V_TOTAL       NUMBER;
    V_EXISTE      NUMBER;
BEGIN
    -- verifica se o cliente existe
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM TBL_CLIENTE
     WHERE ID_CLIENTE = V_ID;

    IF V_EXISTE = 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Cliente nao encontrado para exclusao: ID=' || V_ID);
    END IF;

    -- verifica se possui invoices vinculadas
    SELECT COUNT(*)
      INTO V_TOTAL
      FROM TBL_INVOICE
     WHERE ID_CLIENTE = V_ID;

    IF V_TOTAL > 0 THEN
        -- inativacao logica
        UPDATE TBL_CLIENTE
           SET ATIVO = 'N',
               DATA_ALTERACAO = SYSDATE
         WHERE ID_CLIENTE = V_ID;
    ELSE
        DELETE FROM TBL_CLIENTE
         WHERE ID_CLIENTE = V_ID;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

PROCEDURE PROC_SELECT_CLIENTE (
    V_ID      IN  NUMBER,
    V_CURSOR  OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT C.*
          FROM TBL_CLIENTE C
         WHERE C.ID_CLIENTE = V_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20005, 'Erro ao consultar cliente: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_CLIENTES (
    V_ATIVO   IN  CHAR,
    V_CURSOR  OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT C.*
          FROM TBL_CLIENTE C
         WHERE (V_ATIVO IS NULL OR C.ATIVO = UPPER(V_ATIVO))
         ORDER BY C.NOME_RAZAO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20006, 'Erro ao listar clientes: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_CLIENTES_FILTRO (
    V_PESQUISA IN  VARCHAR2,
    V_CURSOR   OUT SYS_REFCURSOR)
AS
    V_PESQ VARCHAR2(200);
BEGIN
    V_PESQ := '%' || UPPER(TRIM(NVL(V_PESQUISA,''))) || '%';

    OPEN V_CURSOR FOR
        SELECT C.*
          FROM TBL_CLIENTE C
         WHERE (V_PESQUISA IS NULL
                OR UPPER(C.NOME_RAZAO) LIKE V_PESQ
                OR UPPER(NVL(C.NOME_FANTASIA,'')) LIKE V_PESQ
                OR UPPER(NVL(C.DOCUMENTO,'')) LIKE V_PESQ
                OR UPPER(NVL(C.EMAIL,'')) LIKE V_PESQ)
         ORDER BY C.NOME_RAZAO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20007, 'Erro ao pesquisar clientes: ' || SQLERRM);
END;

END PACK_CLIENTE;