CREATE OR REPLACE PACKAGE PACK_INVOICE IS

    FUNCTION FUNC_PROXIMO_INVOICE
        RETURN NUMBER;

    FUNCTION FUNC_GERAR_NUMERO_INVOICE(P_ID NUMBER)
        RETURN VARCHAR2;

    PROCEDURE PROC_INSERT_INVOICE(
        V_INVOICE_NUMBER VARCHAR2,
        V_ID_CLIENTE NUMBER,
        V_ID_REMESSA NUMBER,
        V_ISSUE_DATE DATE,
        V_DUE_DATE DATE,
        V_CURRENCY VARCHAR2,
        V_DISCOUNT_USD NUMBER,
        V_SHIPPING_USD NUMBER,
        V_TAX_USD NUMBER,
        V_CLIENT_EMAIL VARCHAR2,
        V_NOTES VARCHAR2,
        V_ID OUT NUMBER,
        V_NUMBER_OUT OUT VARCHAR2
    );

    PROCEDURE PROC_UPDATE_PATHS(
        V_ID NUMBER,
        V_LOGO_PATH VARCHAR2,
        V_WORD_FILE VARCHAR2,
        V_PDF_FILE VARCHAR2
    );

    PROCEDURE PROC_UPDATE_STATUS(
        V_ID NUMBER,
        V_STATUS VARCHAR2
    );

    PROCEDURE PROC_INSERT_ITEM(
        V_ID_INVOICE NUMBER,
        V_ID_EQUIPAMENTO NUMBER,
        V_DESCRIPTION VARCHAR2,
        V_QTY NUMBER,
        V_UNIT_PRICE_USD NUMBER,
        V_NOTES VARCHAR2
    );

    PROCEDURE PROC_RECALC_TOTAL(
        V_ID_INVOICE NUMBER
    );

    PROCEDURE PROC_SELECT_INVOICE(
        V_ID IN NUMBER,
        V_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_INVOICES(
        V_ID_CLIENTE IN NUMBER,
        V_STATUS IN VARCHAR2,
        V_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_ITENS(
        V_ID_INVOICE IN NUMBER,
        V_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PROC_SELECT_DADOS_DOCUMENTO(
        V_ID_INVOICE IN NUMBER,
        V_CURSOR OUT SYS_REFCURSOR
    );

END PACK_INVOICE;
/

CREATE OR REPLACE PACKAGE BODY PACK_INVOICE IS

FUNCTION FUNC_PROXIMO_INVOICE
RETURN NUMBER
AS
    V_ID NUMBER;
BEGIN
    SELECT SEQ_INVOICE.NEXTVAL INTO V_ID FROM DUAL;
    RETURN V_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'Erro ao obter proximo ID de invoice: ' || SQLERRM);
END;

FUNCTION FUNC_GERAR_NUMERO_INVOICE(P_ID NUMBER)
RETURN VARCHAR2
AS
    V_NUM VARCHAR2(40);
BEGIN
    V_NUM := 'INV-' || TO_CHAR(SYSDATE,'YYYYMMDD') || '-' || LPAD(TO_CHAR(P_ID), 6, '0');
    RETURN V_NUM;
EXCEPTION
    WHEN OTHERS THEN
        V_NUM := 'INV-' || TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS');
        RETURN V_NUM;
END;

PROCEDURE PROC_INSERT_INVOICE(
    V_INVOICE_NUMBER VARCHAR2,
    V_ID_CLIENTE NUMBER,
    V_ID_REMESSA NUMBER,
    V_ISSUE_DATE DATE,
    V_DUE_DATE DATE,
    V_CURRENCY VARCHAR2,
    V_DISCOUNT_USD NUMBER,
    V_SHIPPING_USD NUMBER,
    V_TAX_USD NUMBER,
    V_CLIENT_EMAIL VARCHAR2,
    V_NOTES VARCHAR2,
    V_ID OUT NUMBER,
    V_NUMBER_OUT OUT VARCHAR2
)
AS
    V_IDGERADO NUMBER;
    V_NUMERO VARCHAR2(40);
BEGIN
    V_IDGERADO := FUNC_PROXIMO_INVOICE;
    V_ID := V_IDGERADO;

    IF V_INVOICE_NUMBER IS NULL OR TRIM(V_INVOICE_NUMBER) = '' THEN
        V_NUMERO := FUNC_GERAR_NUMERO_INVOICE(V_IDGERADO);
    ELSE
        V_NUMERO := UPPER(TRIM(V_INVOICE_NUMBER));
    END IF;

    V_NUMBER_OUT := V_NUMERO;

    INSERT INTO TBL_INVOICE
          (ID_INVOICE, INVOICE_NUMBER, ID_CLIENTE, ID_REMESSA, ISSUE_DATE, DUE_DATE,
           CURRENCY, SUBTOTAL_USD, DISCOUNT_USD, SHIPPING_USD, TAX_USD, TOTAL_USD,
           STATUS_INVOICE, CLIENT_EMAIL, NOTES, DATA_CADASTRO)
    VALUES
          (V_IDGERADO, V_NUMERO, V_ID_CLIENTE, V_ID_REMESSA, NVL(V_ISSUE_DATE, TRUNC(SYSDATE)),
           V_DUE_DATE, NVL(UPPER(V_CURRENCY),'USD'), 0, NVL(V_DISCOUNT_USD,0),
           NVL(V_SHIPPING_USD,0), NVL(V_TAX_USD,0), 0, 'DRAFT', LOWER(TRIM(V_CLIENT_EMAIL)),
           V_NOTES, SYSDATE);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20011, 'Erro ao criar invoice: ' || SQLERRM);
END;

PROCEDURE PROC_UPDATE_PATHS(
    V_ID NUMBER,
    V_LOGO_PATH VARCHAR2,
    V_WORD_FILE VARCHAR2,
    V_PDF_FILE VARCHAR2
)
AS
BEGIN
    UPDATE TBL_INVOICE
       SET LOGO_PATH = V_LOGO_PATH,
           WORD_FILE_PATH = V_WORD_FILE,
           PDF_FILE_PATH = V_PDF_FILE,
           DATA_ALTERACAO = SYSDATE
     WHERE ID_INVOICE = V_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'Invoice nao encontrada para atualizar paths: ID=' || V_ID);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

PROCEDURE PROC_UPDATE_STATUS(
    V_ID NUMBER,
    V_STATUS VARCHAR2
)
AS
BEGIN
    IF UPPER(V_STATUS) NOT IN ('DRAFT','SENT','PAID','CANCELLED') THEN
        RAISE_APPLICATION_ERROR(-20013,
            'Status invalido: "' || V_STATUS || '". Valores permitidos: DRAFT, SENT, PAID, CANCELLED.');
    END IF;

    UPDATE TBL_INVOICE
       SET STATUS_INVOICE = UPPER(V_STATUS),
           DATA_ALTERACAO = SYSDATE
     WHERE ID_INVOICE = V_ID;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'Invoice nao encontrada para atualizar status: ID=' || V_ID);
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;

PROCEDURE PROC_INSERT_ITEM(
    V_ID_INVOICE NUMBER,
    V_ID_EQUIPAMENTO NUMBER,
    V_DESCRIPTION VARCHAR2,
    V_QTY NUMBER,
    V_UNIT_PRICE_USD NUMBER,
    V_NOTES VARCHAR2
)
AS
    V_LINE_TOTAL NUMBER(12,2);
BEGIN
    V_LINE_TOTAL := NVL(V_QTY,1) * NVL(V_UNIT_PRICE_USD,0);

    INSERT INTO TBL_INVOICE_ITEM
          (ID_INVOICE_ITEM, ID_INVOICE, ID_EQUIPAMENTO, DESCRIPTION,
           QTY, UNIT_PRICE_USD, LINE_TOTAL_USD, NOTES)
    VALUES
          (SEQ_INVOICE_ITEM.NEXTVAL, V_ID_INVOICE, V_ID_EQUIPAMENTO, V_DESCRIPTION,
           NVL(V_QTY,1), NVL(V_UNIT_PRICE_USD,0), V_LINE_TOTAL, V_NOTES);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20015, 'Erro ao inserir item de invoice: ' || SQLERRM);
END;

PROCEDURE PROC_RECALC_TOTAL(V_ID_INVOICE NUMBER)
AS
    V_SUBTOTAL NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(LINE_TOTAL_USD),0)
      INTO V_SUBTOTAL
      FROM TBL_INVOICE_ITEM
     WHERE ID_INVOICE = V_ID_INVOICE;

    UPDATE TBL_INVOICE
       SET SUBTOTAL_USD = V_SUBTOTAL,
           TOTAL_USD = (V_SUBTOTAL - NVL(DISCOUNT_USD,0) + NVL(SHIPPING_USD,0) + NVL(TAX_USD,0)),
           DATA_ALTERACAO = SYSDATE
     WHERE ID_INVOICE = V_ID_INVOICE;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20016, 'Erro ao recalcular total da invoice: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_INVOICE(
    V_ID IN NUMBER,
    V_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT I.*
          FROM TBL_INVOICE I
         WHERE I.ID_INVOICE = V_ID;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20017, 'Erro ao consultar invoice: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_INVOICES(
    V_ID_CLIENTE IN NUMBER,
    V_STATUS IN VARCHAR2,
    V_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT I.ID_INVOICE,
               I.INVOICE_NUMBER,
               I.ID_CLIENTE,
               C.NOME_RAZAO AS CLIENTE_NOME,
               I.ID_REMESSA,
               I.ISSUE_DATE,
               I.DUE_DATE,
               I.SUBTOTAL_USD,
               I.DISCOUNT_USD,
               I.SHIPPING_USD,
               I.TAX_USD,
               I.TOTAL_USD,
               I.STATUS_INVOICE,
               I.CLIENT_EMAIL,
               I.DATA_CADASTRO
          FROM TBL_INVOICE I
          JOIN TBL_CLIENTE C ON I.ID_CLIENTE = C.ID_CLIENTE
         WHERE (V_ID_CLIENTE IS NULL OR I.ID_CLIENTE = V_ID_CLIENTE)
           AND (V_STATUS IS NULL OR I.STATUS_INVOICE = UPPER(V_STATUS))
         ORDER BY I.DATA_CADASTRO DESC;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20018, 'Erro ao listar invoices: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_ITENS(
    V_ID_INVOICE IN NUMBER,
    V_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT II.ID_INVOICE_ITEM,
               II.ID_INVOICE,
               II.ID_EQUIPAMENTO,
               II.DESCRIPTION,
               II.QTY,
               II.UNIT_PRICE_USD,
               II.LINE_TOTAL_USD,
               II.NOTES,
               E.INTERNAL_UID,
               E.MARCA,
               E.MODEL
          FROM TBL_INVOICE_ITEM II
          LEFT JOIN TBL_EQUIPAMENTO E ON E.ID_EQUIPAMENTO = II.ID_EQUIPAMENTO
         WHERE II.ID_INVOICE = V_ID_INVOICE
         ORDER BY II.ID_INVOICE_ITEM;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20019, 'Erro ao listar itens da invoice: ' || SQLERRM);
END;

PROCEDURE PROC_SELECT_DADOS_DOCUMENTO(
    V_ID_INVOICE IN NUMBER,
    V_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN V_CURSOR FOR
        SELECT I.ID_INVOICE,
               I.INVOICE_NUMBER,
               I.ISSUE_DATE,
               I.DUE_DATE,
               I.CURRENCY,
               I.SUBTOTAL_USD,
               I.DISCOUNT_USD,
               I.SHIPPING_USD,
               I.TAX_USD,
               I.TOTAL_USD,
               I.STATUS_INVOICE,
               I.CLIENT_EMAIL,
               I.NOTES,
               I.LOGO_PATH,
               I.WORD_FILE_PATH,
               I.PDF_FILE_PATH,
               I.ID_REMESSA,
               C.ID_CLIENTE,
               C.NOME_RAZAO,
               C.NOME_FANTASIA,
               C.DOCUMENTO,
               C.EMAIL AS EMAIL_CLIENTE,
               C.TELEFONE,
               C.ENDERECO1,
               C.ENDERECO2,
               C.CIDADE,
               C.ESTADO,
               C.ZIP_CODE,
               C.PAIS
          FROM TBL_INVOICE I
          JOIN TBL_CLIENTE C ON I.ID_CLIENTE = C.ID_CLIENTE
         WHERE I.ID_INVOICE = V_ID_INVOICE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20020, 'Erro ao carregar dados do documento: ' || SQLERRM);
END;

END PACK_INVOICE;
/
