-- ============================================================================
-- GBS Inventory - Add battery/condition status to equipment
-- Execute as GBS_OWNER before recompiling PACK_EQUIPAMENTO.
-- ============================================================================

DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_COUNT
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TBL_EQUIPAMENTO'
       AND COLUMN_NAME = 'CONDITION_STATUS';

    IF V_COUNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_EQUIPAMENTO ADD CONDITION_STATUS VARCHAR2(20) DEFAULT ''GOOD''';
    END IF;
END;
/

ALTER TABLE TBL_EQUIPAMENTO
  MODIFY CONDITION_STATUS DEFAULT 'GOOD';

UPDATE TBL_EQUIPAMENTO
   SET CONDITION_STATUS = NULL
 WHERE CONDITION_STATUS IS NOT NULL
   AND CONDITION_STATUS NOT IN ('EXCELLENT','GOOD','FAIR','POOR');

UPDATE TBL_EQUIPAMENTO
   SET CONDITION_STATUS = 'GOOD'
 WHERE CONDITION_STATUS IS NULL;

BEGIN
    FOR C IN (
        SELECT DISTINCT CONSTRAINT_NAME
          FROM USER_CONS_COLUMNS
         WHERE TABLE_NAME = 'TBL_EQUIPAMENTO'
           AND COLUMN_NAME = 'CONDITION_STATUS'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_EQUIPAMENTO DROP CONSTRAINT ' || C.CONSTRAINT_NAME;
    END LOOP;
END;
/

ALTER TABLE TBL_EQUIPAMENTO
  ADD CONSTRAINT CK_EQUIP_CONDITION
  CHECK (CONDITION_STATUS IN ('EXCELLENT','GOOD','FAIR','POOR'));

COMMIT;
